name: Deploy Infrastructure with Terragrunt

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TG_PARALLELISM: 4
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_S3_BUCKET_NAME: "navirego-dev-sftp-dump"
      TF_VAR_SFTP_PASS: "o3gnBzJPL1P0KHgQb051uVtIrHvCq6N0tNJ23bEpSmGzD"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Install Terragrunt
        run: |
          wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.4/terragrunt_linux_amd64 > terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Make all shell scripts executable
        run: |
          echo " Setting execute permissions for all .sh files..."
          find . -type f -name "*.sh" -exec chmod +x {} \;

      - name: Run deploy-all.sh before Terragrunt plan
        working-directory: ./scripts
        run: |
          ./deploy-all.sh

      - name: Run Terragrunt plan (dev)
        working-directory: ./live/dev
        run: |
          echo "ðŸ§© Using TF_VAR_S3_BUCKET_NAME=$TF_VAR_S3_BUCKET_NAME"
          echo "ðŸ§© Using TF_VAR_SFTP_PASS=$TF_VAR_SFTP_PASS"
          echo "ðŸ§© Using TF_VAR_DB_PASSWORD=$TF_VAR_DB_PASSWORD"
          terragrunt run-all destroy --terragrunt-non-interactive -auto-approve